/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Mon, Jul 20, 2015                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :RX210                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
// #pragma stacksize si=0x300      
#pragma stacksize si=0x600          // 20160428
